// <auto-generated />
using System;
using Illumination.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Illumination.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IlluminationDbContext))]
    [Migration("20260809050452_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AcceptedShortAnswerRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("LearningItemId", "Position");

                    b.ToTable("AcceptedShortAnswers", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AnswerChoiceRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsCorrect");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("LearningItemId", "Role", "Position");

                    b.ToTable("AnswerChoices", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningItemRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.HasKey("DeckId", "LearningItemId");

                    b.HasIndex("LearningItemId");

                    b.ToTable("DeckLearningItems", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("DeckId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.HintRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("LearningItemId", "Position");

                    b.ToTable("Hints", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<string>("DueAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DueAt");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsNew");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LifecycleState");

                    b.Property<bool>("LowInteractionEligible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LowInteractionEligible");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Prompt");

                    b.Property<string>("ReferenceSolutionContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReferenceSolutionContent");

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ResponseMode");

                    b.HasKey("LearningItemId");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("IX_LearningItems_DueAt");

                    b.ToTable("LearningItems", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AcceptedShortAnswerRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("AcceptedShortAnswers")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AnswerChoiceRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("AnswerChoices")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningItemRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.DeckRecord", "Deck")
                        .WithMany("Memberships")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("DeckMemberships")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.HintRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("Hints")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckRecord", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemRecord", b =>
                {
                    b.Navigation("AcceptedShortAnswers");

                    b.Navigation("AnswerChoices");

                    b.Navigation("DeckMemberships");

                    b.Navigation("Hints");
                });
#pragma warning restore 612, 618
        }
    }
}
