// <auto-generated />
using System;
using Illumination.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Illumination.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IlluminationDbContext))]
    partial class IlluminationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AcceptedShortAnswerRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("LearningItemId", "Position");

                    b.ToTable("AcceptedShortAnswers", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AnswerChoiceRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<string>("ChoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ChoiceId");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsCorrect");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("LearningItemId", "Role", "Position");

                    b.HasIndex("LearningItemId", "Role", "ChoiceId")
                        .IsUnique();

                    b.ToTable("AnswerChoices", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningActivityProfileRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Profile");

                    b.HasKey("DeckId", "Profile");

                    b.HasIndex("Profile")
                        .HasDatabaseName("IX_DeckLearningActivityProfiles_Profile");

                    b.ToTable("DeckLearningActivityProfiles", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningItemRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.HasKey("DeckId", "LearningItemId");

                    b.HasIndex("LearningItemId");

                    b.ToTable("DeckLearningItems", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("DeckId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckTopicLabelRecord", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeckId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE")
                        .HasColumnName("Label");

                    b.HasKey("DeckId", "Label");

                    b.HasIndex("Label")
                        .HasDatabaseName("IX_DeckTopicLabels_Label");

                    b.ToTable("DeckTopicLabels", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.HintRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("LearningItemId", "Position");

                    b.ToTable("Hints", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.ImportProvenanceRecord", b =>
                {
                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportBatchId");

                    b.Property<int>("AcceptedOperationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Contract");

                    b.Property<int>("CreatedDeckCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedLearningItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalBundleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExternalBundleId");

                    b.Property<string>("GeneratedFor")
                        .HasColumnType("TEXT")
                        .HasColumnName("GeneratedFor");

                    b.Property<string>("ImportedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportedAt");

                    b.Property<int>("UpdatedDeckCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedLearningItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Version");

                    b.HasKey("ImportBatchId");

                    b.ToTable("ImportProvenance", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<int>("ContentRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("ContentRevision");

                    b.Property<double>("Difficulty")
                        .HasColumnType("REAL")
                        .HasColumnName("Difficulty");

                    b.Property<string>("DueAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DueAt");

                    b.Property<bool>("IsInShortTermRelearning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsInShortTermRelearning");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsNew");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LifecycleState");

                    b.Property<bool>("LowInteractionEligible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LowInteractionEligible");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Prompt");

                    b.Property<string>("ReferenceSolutionContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReferenceSolutionContent");

                    b.Property<string>("ResponseMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ResponseMode");

                    b.Property<double>("StabilityDays")
                        .HasColumnType("REAL")
                        .HasColumnName("StabilityDays");

                    b.HasKey("LearningItemId");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("IX_LearningItems_DueAt");

                    b.ToTable("LearningItems", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemUserFlagRecord", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserFlagDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId", "UserFlagDefinitionId");

                    b.HasIndex("UserFlagDefinitionId");

                    b.ToTable("LearningItemUserFlags", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.QualityReviewRecord", b =>
                {
                    b.Property<Guid>("QualityReviewId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedCorrection")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("TEXT");

                    b.HasKey("QualityReviewId");

                    b.HasIndex("SupersededBy");

                    b.HasIndex("LearningItemId", "ContentRevision");

                    b.ToTable("QualityReviews", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.ReviewRecord", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewId");

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Assessment");

                    b.Property<bool>("AssistanceAnswerChoicesRevealed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AssistanceAnswerChoicesRevealed");

                    b.Property<bool?>("AutomaticCorrectness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AutomaticCorrectness");

                    b.Property<string>("CompletedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CompletedAt");

                    b.Property<int>("HintCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HintCount");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.Property<bool>("ReferenceSolutionRevealed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReferenceSolutionRevealed");

                    b.Property<string>("SubmittedResponse")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubmittedResponse");

                    b.Property<string>("SuggestedAssessment")
                        .HasColumnType("TEXT")
                        .HasColumnName("SuggestedAssessment");

                    b.HasKey("ReviewId");

                    b.HasIndex("LearningItemId")
                        .HasDatabaseName("IX_Reviews_LearningItemId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudyPreferenceRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("DefaultEvaluationMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultEvaluationMode");

                    b.HasKey("Id");

                    b.ToTable("StudyPreferences", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionDeckRecord", b =>
                {
                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudySessionId", "DeckId");

                    b.ToTable("StudySessionDecks", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionQueueRecord", b =>
                {
                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LearningItemId");

                    b.HasKey("StudySessionId", "Position");

                    b.ToTable("StudySessionQueue", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionRecord", b =>
                {
                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("StudySessionId");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompletedAt");

                    b.Property<bool>("ConsiderAssistance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ConsiderAssistance");

                    b.Property<string>("EvaluationMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EvaluationMode");

                    b.Property<bool>("LowInteractionOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LowInteractionOnly");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StartedAt");

                    b.HasKey("StudySessionId");

                    b.ToTable("StudySessions", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionReviewRecord", b =>
                {
                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudySessionId", "Position");

                    b.HasIndex("ReviewId");

                    b.ToTable("StudySessionReviews", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.UserFlagDefinitionRecord", b =>
                {
                    b.Property<Guid>("UserFlagDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserFlagDefinitionId");

                    b.ToTable("UserFlagDefinitions", (string)null);
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AcceptedShortAnswerRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("AcceptedShortAnswers")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.AnswerChoiceRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("AnswerChoices")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningActivityProfileRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.DeckRecord", "Deck")
                        .WithMany("LearningActivityProfiles")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckLearningItemRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.DeckRecord", "Deck")
                        .WithMany("Memberships")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("DeckMemberships")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckTopicLabelRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.DeckRecord", "Deck")
                        .WithMany("TopicLabels")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.HintRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("Hints")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemUserFlagRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("UserFlagAssignments")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illumination.Infrastructure.Persistence.UserFlagDefinitionRecord", "UserFlagDefinition")
                        .WithMany()
                        .HasForeignKey("UserFlagDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningItem");

                    b.Navigation("UserFlagDefinition");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.QualityReviewRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany("QualityReviews")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illumination.Infrastructure.Persistence.QualityReviewRecord", null)
                        .WithMany()
                        .HasForeignKey("SupersededBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.ReviewRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.LearningItemRecord", "LearningItem")
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionDeckRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.StudySessionRecord", "StudySession")
                        .WithMany("SelectedDecks")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionQueueRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.StudySessionRecord", "StudySession")
                        .WithMany("Queue")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionReviewRecord", b =>
                {
                    b.HasOne("Illumination.Infrastructure.Persistence.ReviewRecord", "Review")
                        .WithMany("StudySessionAssociations")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illumination.Infrastructure.Persistence.StudySessionRecord", "StudySession")
                        .WithMany("Reviews")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.DeckRecord", b =>
                {
                    b.Navigation("LearningActivityProfiles");

                    b.Navigation("Memberships");

                    b.Navigation("TopicLabels");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.LearningItemRecord", b =>
                {
                    b.Navigation("AcceptedShortAnswers");

                    b.Navigation("AnswerChoices");

                    b.Navigation("DeckMemberships");

                    b.Navigation("Hints");

                    b.Navigation("QualityReviews");

                    b.Navigation("UserFlagAssignments");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.ReviewRecord", b =>
                {
                    b.Navigation("StudySessionAssociations");
                });

            modelBuilder.Entity("Illumination.Infrastructure.Persistence.StudySessionRecord", b =>
                {
                    b.Navigation("Queue");

                    b.Navigation("Reviews");

                    b.Navigation("SelectedDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
